# Generated by Django 6.0.1 on 2026-01-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deposite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposite",
            name="deposite_id",
        ),
    ]
