# Generated by Django 6.0.1 on 2026-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="Type",
            new_name="type",
        ),
        migrations.AddField(
            model_name="plan",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
