# Generated by Django 6.0.1 on 2026-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
    ]
