# Generated by Django 6.0.1 on 2026-01-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_alter_expense_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="expense_id",
        ),
    ]
