# Generated by Django 6.0.1 on 2026-01-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("deposite", "0001_initial"),
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("credit_amt", models.IntegerField()),
                ("debit_amt", models.IntegerField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_id",
                        to="customer.customer",
                    ),
                ),
                (
                    "deposit_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposite_type_id",
                        to="deposite.deposite",
                    ),
                ),
                (
                    "expense_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_type_id",
                        to="expense.expense",
                    ),
                ),
            ],
        ),
    ]
