# Generated by Django 6.0.1 on 2026-01-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("deposite", "0001_initial"),
        ("expense", "0001_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="deposit_type_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="expense_type_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="deposit_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="f_deposite_id",
                to="deposite.deposite",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="expense_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="f_expense_id",
                to="expense.expense",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="credit_amt",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="f_customer_id",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="debit_amt",
            field=models.IntegerField(default=0),
        ),
    ]
