# Generated by Django 6.0.1 on 2026-01-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_remove_transaction_deposit_type_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="deposit_id",
            new_name="deposite_id",
        ),
    ]
